# Generated by Django 3.0.6 on 2020-05-14 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='Имя абонента')),
                ('mobile_phone', models.IntegerField(null=True, verbose_name='Мобильный телефон')),
                ('second_mobile_phone', models.IntegerField(null=True, verbose_name='Доп. моб. телефон')),
                ('home_phone', models.IntegerField(null=True, verbose_name='Домашний телефон')),
                ('work_phone', models.IntegerField(null=True, verbose_name='Рабочий телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
